### ISSUE TITLE
Close Calendar by tapping on the grey area

### ISSUE THREAD

**Issue by LuongTruong** [react-native-community/datetimepicker#112]
# Question
Do we have any work around so that when users tap on the grey area, the calendar should be closed.

# Current behavior
Tapping on the grey area doesn't take any effect
# Expect behavior
Tapping on the grey area calendar will be close, like we press the cancel button.

Thank you in advanced!

**Comment by jsbeckr** [comment]
Isn't that the case?

I am using `"@react-native-community/datetimepicker": "^2.2.3"` and if tap on the backdrop outside of the calendar component, the calendar closes.

And the `event` in the `onChange` handler has `type: "dismissed"`

**Comment by vonovak** [comment]
hello, thanks for reporting; I'm closing this because it does not follow the issue template, so it's hard to help.
