### ISSUE TITLE
DatePicker on spinner mode not working on some Phones

### ISSUE THREAD

**Issue by otaviogaiao** [react-native-community/datetimepicker#117]
# Bug

I'm trying to use the datepicker on spinner mode with Expo, but on some devices, it shows the calendar mode.

I tested on an emulator with Android SDK 24 and the problem occurs.

On SDK 26 and 29 the datepicker worked on the emulators. However, After I build the app with expo, it doesn't work on any phone.

I created a repo here:

https://github.com/otaviogaiao/teste-datepicker

The problem is basically the same one stated here: https://github.com/react-native-community/react-native-datetimepicker/issues/76

## Environment info

Expo SDK 36
react-native-datepicker 2.2.2

**Comment by luancurti** [comment]
Hi @otaviogaiao thanks for the report. I've tested you demo and I managed to reproduce this problem. I'll investigate this

**Comment by otaviogaiao** [comment]
> Hi @otaviogaiao thanks for the report. I've tested your demo and I managed to reproduce this problem. I'll investigate this. But in our exemple this bug doesn't occurs 😐

You are welcome. Hope you can fix it! This is the best library available :)

**Comment by mafiusu** [comment]
Hey I faced this bug today where the spinner mode appears on expo development mode but not in the production store version of my application. Can anyone tell me why this is happening?

**Comment by shahmeerkhalid** [comment]
The problem still persists.

**Comment by vonovak** [comment]
@mafiusu @shahmeerkhalid please open a new issue and follow the template, thank you!
