### ISSUE TITLE
Remove timeZoneOffsetInMinutes={0} from example

### ISSUE THREAD

**Issue by UberMC** [react-native-community/datetimepicker#121]
# Feature Request

I recommend removing timeZoneOffsetInMinutes={0} from example code, or change it to grab the local timezone offset. My fault for grabbing this example code so hastly but why would someone want to display UTC time to a client in an app, I know It's a feature to the component however I wasted like 3 hours until I realized that prop timeZoneOffsetInMinutes

**Comment by eroy4u** [comment]
Support! that's really useless to display to display UTC time

**Comment by dariuscosden** [comment]
> but why would someone want to display UTC time to a client in an app

Simple. Birthdays. Your birthday should be displayed on the same date regardless of timezone.

**Comment by Kiura** [comment]
> @UberMC
> 
> > but why would someone want to display UTC time to a client in an app
> 
> Simple. Birthdays. Your birthday should be displayed on the same date regardless of timezone.

Exactly! I spent half an hour trying to figure out why the date is different. I used UTC for birthday and the library kept showing a day before my birthday and it wasn't clear `timeZoneOffsetInSeconds={0}` will make it UTC. Moreover, if I set `timeZoneOffsetInMinutes={0} will not make it UTC, I believe it set GMT, which is very weird, I expected those two to behave exactly the same

**Comment by tabbycat-dev** [comment]
Instead you could you 

> > @UberMC
> > > but why would someone want to display UTC time to a client in an app
> > 
> > 
> > Simple. Birthdays. Your birthday should be displayed on the same date regardless of timezone.
> 
> Exactly! I spent half an hour trying to figure out why the date is different. I used UTC for birthday and the library kept showing a day before my birthday and it wasn't clear `timeZoneOffsetInSeconds={0}` will make it UTC. Moreover, if I set `timeZoneOffsetInMinutes={0}` will not make it UTC, I believe it set GMT, which is very weird, I expected those two to behave exactly the same
Instead you could use timeZoneName={'GMT'} or any timezone name that have UTC +0 on the list https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
