### ISSUE TITLE
[xcode 10] Build crashes

### ISSUE THREAD

**Issue by alexktzk** [react-native-community/datetimepicker#133]
# Bug

Build crashes on IOS, because [labelColor variable](https://github.com/react-native-community/datetimepicker/blob/66be0879c324a69d250d5e6067b0f69683901f80/ios/RNDateTimePickerManager.m#L51) does not exist.

Actual error message:
```
.../node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:51:33: 
error: no known class method for selector 'labelColor'
        defaultColor = [UIColor labelColor];
```

## Environment info

Library version: 2.3.0
IOS: 13.2.2

**Comment by ShenAizhen** [comment]
Same error for me. I think that last commit to this file causes this error.

**Comment by deborahhellen** [comment]
+1 also seeing the same issue.

**Comment by alexktzk** [comment]
@ShenAizhen you're right, the problem appeared with [this commit](https://github.com/react-native-community/datetimepicker/commit/54c20bdfc665dfbacbf716d5f7a5b5d50806f084).

I used the previous version for now. Just in case, the version in **package.json** must be without **^**, because otherwise it actually installs 2.3.0 when you run **pod install**
```
"@react-native-community/datetimepicker": "2.2.3",
```
not
```
"@react-native-community/datetimepicker": "^2.2.3",
```

**Comment by vonovak** [comment]
hello, what xcode version are you folks using? Thanks

**Comment by omerman** [comment]
Happens to me as well.

@vonovak 
Xcode 10.2.1
Build version 10E1001

**Comment by vonovak** [comment]
upgrading to xcode 11 should fix this I think

**Comment by vonovak** [comment]
hello, if someone needs to support xcode 10, please open a PR that fixes the compilation in xcode 10. Maintainers will not be adding that support because we plan to fix more pressing issues, thank you.
