### ISSUE TITLE
Compile Build failing for react-native 0.62 (IOS)

### ISSUE THREAD

**Issue by rahulkasana** [react-native-community/datetimepicker#145]
# Bug

When running react-native run-ios build fails.

The following build commands failed:
        CompileC /Users/rkasana/Library/Developer/Xcode/DerivedData/ZastOnmove-ghuhgjztjiovtxbhhzofecqaqfnv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNDateTimePicker.build/Objects-normal/x86_64/RNDateTimePickerManager.o /Users/rkasana/Documents/onmove/NewLennon/lennon/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

My podfile contains -
pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'

## Environment info
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 168.34 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 10.0/10A255 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 2.3.1

## Steps To Reproduce
1. npm install @react-native-community/datetimepicker --save
2. cd ios && pod install && cd ..
3. Tried to run react-native run-ios (Build failing and unable to run ios).

Describe what you expected to happen:

1. Project to run properly

**Comment by rahulkasana** [comment]
Is the issue maybe caused coz I don't have `use_frameworks` enabled ?

**Comment by constantin-onu** [comment]
I have the same problem ... It is working fine with RN 0.61.5 but with RN 0.62.1 I have the same error.

**Comment by luancurti** [comment]
@rahulkasana thanks for report this problem, I'm working in the solution in the PR #146 I need to test the `Android Example App` to make a `Example App` working with `react native 0.62.2` I'll make this in the next days, when this PR #146 is merged I'll send a next version of the library in the `npm` and fix this issue, thanks again!

**Comment by drachyovmaxim** [comment]
same issue
temporary solution is changing RNDateTimePickerManager.m
```
if (@available(iOS 13.0, *)) {
        defaultColor = [UIColor labelColor];
    } else {
        defaultColor = [UIColor blackColor];
    }
```
to
```
defaultColor = [UIColor blackColor];
```

**Comment by luancurti** [comment]
@drachyovmaxim this is not you issue your issue is #133 I'm working in the fix, thanks for the report

**Comment by luigbren** [comment]
Hi.. Report same problem in RN 0.62.1, build fail :(

**Comment by luancurti** [comment]
@rahulkasana if you use `use_native_modules!` you could remove this line `pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'` of your `Podfile`

**Comment by luancurti** [comment]
This issue is closed because we have an example working with `0.62.2` version

**Comment by enriquehudson** [comment]
I had the same problem, I only have to Update Xcode 10 to 11
After that, I tested with iOs 12 and works without problems

**Comment by ZainAliSyed24** [comment]
> @rahulkasana if you use `use_native_modules!` you could remove this line `pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'` of your `Podfile`

**Still not working . I have tried installing both version** 

"@react-native-community/datetimepicker": "^3.0.1”,

"@react-native-community/datetimepicker": "^2.5.0",

**Comment by luancurti** [comment]
Hi guys, don't forgot to use the Xcode 11.6 if you update to version 3+

**Comment by apswak** [comment]
Got this when updating to Big Sur. Fixed it by updating Xcode to latest version **and** opening the simulator then selecting `Device > Erase all contents and settings...` on top Menu, then closing simulator + rerunning `yarn ios`.

**Comment by olesia-ag** [comment]
is there a solution for 0.63.3 ?

**Comment by umaraziz0** [comment]
Hello, sorry to re-open this discussion as I'm stuck on the same problem and don't want to create a new duplicate issue. 

My error message is as follows

> The following build commands failed:
        CompileC /Users/user/Library/Developer/Xcode/DerivedData/newProject-fbtmyswxmwvojjbtrwllttvccavn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNDateTimePicker.build/Objects-normal/arm64/RNDateTimePickerShadowView.o /Users/user/Sites/new-project/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNDateTimePicker' from project 'Pods')
(1 failure)

- xCode version: xCode 14.2
- iOS simulator version: iOS 16.2

Have also tried using
- xCode v15
- iOS v17

- React Native version: 0.67.4

my `Podfile` contains
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'newProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'newProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

Environment Info
```
System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 95.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by TeyimPila** [comment]
@umaraziz0 were you able to find a solution to this issue?

**Comment by umaraziz0** [comment]
> @umaraziz0 were you able to find a solution to this issue? I am still facing the same issue and am unable to find a fix for it

Not yet unfortunately, I've put it in my backlog for now. Hopefully someone else can provide some help

**Comment by Gautamshah1** [comment]
emed4u.com/Library/Developer/Xcode/DerivedData/EMed4UMobileApp-fwymcedhgqrbkwclwyrzlvzkiyai/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNDateTimePicker.build/Objects-normal/arm64/RNDateTimePickerShadowView.o

getting this error while i am using ios12
