### ISSUE TITLE
Malformed calls after opening after modal is closed and reopened

### ISSUE THREAD

**Issue by KjellConnelly** [react-native-community/datetimepicker#150]
# Bug

I'm getting a yellow error: Exception in HostFunction: Malformed calls from JS: field sizes are different. This happens when I open a modal that contains a datetimepicker component in it, open the datetimepicker, close datetimepicker, close modal, reopen modal, and try to open datetimepicker again (but fails and results in yellow screen with no datetimepicker being shown)

<img width="535" alt="Screen Shot 2020-04-17 at 3 34 02 PM" src="https://user-images.githubusercontent.com/13230597/79619732-9466d780-80c2-11ea-84a8-288c53d66432.png">

## Environment info

"@react-native-community/datetimepicker": "^2.3.2",

`react-native info` output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.14 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.3.2

## Steps To Reproduce
1. Open datetimepicker in Modal (via <Button onPress{...} /> and close it at least once.
2. Close modal
3. Reopen modal
4. Try to open datetimepicker 
...

Describe what you expected to happen:

1. Expecting datetimepicker to open like it did before I closed the modal the first time

## Reproducible sample code

This is tested on android so far only.
```javascript
import React, { Component, } from 'react'
import {View, Button, Modal} from 'react-native'
import DateTimePicker from '@react-native-community/datetimepicker'
```

```jsx
<Button onPress={()=>{this.setState({show:!show})}}>
  {"Show Datetimepicker"}
</Button>
{show &&
<DateTimePicker
  value={date}
  mode='time'
  display="spinner"
  onChange={(event, newDate)=>{
    this.setState({date:newDate,show:false})
  }}/>
}
```

**Comment by vonovak** [comment]
Hello and thank you for reporting. You're mentioning modal, but modal is not even used in the sample. Please update your code sample to be a *runnable* reproduction.  Even better put it in a expo snack. Thank you.

**Comment by riamon-v** [comment]
Same issue here

**Comment by vonovak** [comment]
Hi there! Sorry you're having an issue. As the issue template explains, we require that you provide a runnable example that reproduces your issue (see the issue template). The reason is that maintainers do not have time to try reproduce bugs themselves. Please try to minimize the superfluous code and focus only on reproducing the bug.

Please create a new issue with this and we'll be happy to review it!
