### ISSUE TITLE
How does the iOS class Picker get resolved to the RNDateTimePicker component?

### ISSUE THREAD

**Issue by rectified95** [react-native-community/datetimepicker#153]
# Question

I'm having trouble understanding how the iOS version of the component is wired up. index.js exports RNDateTimePicker, which it imports from './datetimepicker'. 
The datetimepicker.ios.js file exports the Picker class - it's not named RNDateTimePicker. Why is this the case?
Meanwhile the Android component is defined in the 'normal' way as follows: 
`export default function RNDateTimePicker`.

**Comment by vonovak** [comment]
hello, the modules use default exports and a default export can be imported under an arbitrary name. You can read more about this in https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

does this answer the question?

**Comment by rectified95** [comment]
Yes, thanks for clarifying and the quick response. 
Closing.
