### ISSUE TITLE
IllegalStateException: Native module TimePicker Android tried to override com.facebook.react.modules.timepicker.TimePickerD

### ISSUE THREAD

**Issue by gokulkulkarni1987** [react-native-community/datetimepicker#154]
# Bug

When we get upgraded our project to rn-0.62.2 we started getting the below error,

```
IllegalStateException: Native module TimePicker Android tried to override com.facebook.react.modules.timepicker.TimePickerD
```
## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.11 GB / 15.89 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: Not Found
    Python: 2.7.17 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 8.6.0

## Steps To Reproduce

1. Upgraded existing project from rn 0.59.9 to 0.62.2
2. Ran the project
...

Describe what you expected to happen:

Build must be successful.

**Comment by luancurti** [comment]
@gokulkulkarni1987 do you have any reproducible demo? I've a example using the `0.62.2` without problems, I suggest you check it

**Comment by gokulkulkarni1987** [comment]
@luancurti it is happening in our company project. Cant share the code, I will check your example once.

**Comment by gokulkulkarni1987** [comment]
Got the issue.

Culprit was `new MainReactPackage()` in `getPackages()` had forgot to remove that.

Thanks for your support @luancurti
