### ISSUE TITLE
Is there RTL support for android?

### ISSUE THREAD

**Issue by avirankatzsofi** [react-native-community/datetimepicker#156]
# Question

Using the `DateTimePicker` on an RTL android app shows an LTR dialog - action buttons are aligned to the right, The week starts at the left side of the dialog etc.
I haven't found any issues mentioning RTL, nor any mentions on stackoverflow.
Is RTL support implemented? Is it going to be implemented in the future?

**Comment by vonovak** [comment]
hello, I honestly don't know; if it does not work then we probably don't support it. We would be open to merging a PR that adds RTL support, would you be interested in contributing that?

**Comment by avirankatzsofi** [comment]
After digging a bit I found out that what I had experienced isn't related to the library, but to a broader setting that was missing from `AndroidManifest.xml`.

In case anyone stumbles upon this issue in the future, that's what I did to fix it:
Inside `AndroidManifest.xml`, append `application` with:

    android:supportsRtl="true"
