### ISSUE TITLE
Accessing the ok button of the calendar

### ISSUE THREAD

**Issue by gagan-aryan** [react-native-community/datetimepicker#162]
# Question
I am building a screen and I want the user to land to the time-picker after pressing 'OK' on the date-picker. But I am unable to do that. Can someone help me with this?

**Comment by soyjesus** [comment]
I think the only way is using another picker like https://github.com/xgfe/react-native-datepicker :/

**Comment by vonovak** [comment]
I deleted the comment because it was misleading. 

@gagan-aryan what you need to do is 

1. open date-picker
2. user presses 'OK'
3. hide date-picker
4. open time-picker
5. user presses 'OK'
6. close time-picker

hope this helps!

**Comment by LucasHimelfarb** [comment]
?????????????????????????????????

I'm sure you've asked what the accessory is to handle that event....
