### ISSUE TITLE
iOS Crash when doing a lot of date changes.

### ISSUE THREAD

**Issue by kyytiPetteri** [react-native-community/datetimepicker#168]
# Bug report

## Summary

Chaging dates and time quickly with the `datetime` picker causes the app to crash on iOS with the following error message:

`Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x281259170> was mutated while being enumerated.'`

## Environment info

`react-native info` output:
```bash
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 122.74 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5
```

Library version: 2.4.0

## Steps to reproduce

Problem can reproduced by constantly changing the date and letting is set and changing it again. When the crash happens, varies.

Reproducible also only on a device and not on simulators

Describe what you expected to happen:

No crash!

## Reproducible sample code

Ive set component in the following matter:
```
     const [tempDate, setTempDate] = useState(newDate);
     const onChangeDate = (_: Event, date: Date) => setTempDate(date);

    <RNDateTimePicker
      value={moment(value).toDate()}
      mode="datetime"
      onChange={onChange}
      minimumDate={minimumDate}
      maximumDate={maximumDate}
    />
```

**Comment by vonovak** [comment]
Hello, thank you. Can you please share

- full stacktrace
- code snippet that can be copy pasted into an empty file which reproduces this
- video recording would help

this is ios 13.4 simulator, correct?

**Comment by kyytiPetteri** [comment]
Does not seem to be an issue related to this lib since the problem does not repro when set into a very simple screen/component. The original crash does still happen only when changing dates. 

Closing this for now until there is a better understanding of the issue. Will keep on commenting here is a solution is found
