### ISSUE TITLE
Customize styles and locale are not supported on android

### ISSUE THREAD

**Issue by MortadhaFadhlaoui** [react-native-community/datetimepicker#176]
**This component is useless without customizing styles and locale on Android**

**Comment by MortadhaFadhlaoui** [comment]
_Okay when i change mode to spinner i don't worry about that any more, thanks_

**Comment by vonovak** [comment]
closing as a duplicate of https://github.com/react-native-community/datetimepicker/issues/82 and https://github.com/react-native-community/datetimepicker/issues/20
