### ISSUE TITLE
Talkback - Reading order is not logical/intuitive

### ISSUE THREAD

**Issue by rodrieja** [react-native-community/datetimepicker#188]
# Question

Hi, we are having problems to use the time picket when Talkback is enabled. This is what is happening and I'd love to know if there is a way to handle or fix it. 

Thanks!

As a talkback user, the reading order must be logical so that the users can understand the structure of the page. 

Current behaviour: 
1. As a Talkback user, swipe through the enter time widget. 
2. the following order is observed. 
a. hour edit field 
b. colon symbol 
c. minute edit field 
d. hour label 
e. Minute label 

Expected behaviour: 
1. As a Talkback user, swipe through the enter time widget. 
2. The following order is expected 
a. hour edit field 
b. hour label 
c. colon symbol 
d. minute edit field 
e. Minute label

## First focus
![image](https://user-images.githubusercontent.com/8691226/83294429-ad839d80-a1c3-11ea-9b58-1d2aaa658eee.png)

## Second focus
![image](https://user-images.githubusercontent.com/8691226/83294458-bc6a5000-a1c3-11ea-9d02-e6c4d1d39d96.png)

## Third focus
![image](https://user-images.githubusercontent.com/8691226/83294592-eae82b00-a1c3-11ea-8e65-c9a325ad9109.png)

## Fourth focus
![image](https://user-images.githubusercontent.com/8691226/83294630-f9364700-a1c3-11ea-9050-6d115bc23eeb.png)

## Fifth focus
![image](https://user-images.githubusercontent.com/8691226/83294674-08b59000-a1c4-11ea-9f5b-31592bb633ff.png)

**Comment by rectified95** [comment]
I'm not very familiar with the Android side of things here, but my hunch is you should report this issue in the RN repo, rather than here. The rendering of the layout is the job of the platform-specific code in the RN repo.

@vonovak to confirm if we have Android accessibility code in this repo, and close otherwise.

**Comment by vonovak** [comment]
Hello and thanks for asking. React Native itself is not involved at all with what is presented / rendered and how accessibility is handled here. We just display a dialog that is provided by the Android sdk.

While the question is valid, I think stackoverflow or some Android-specific place would be a better fit for asking this. I'm not able to give a better answer than this so I'm going to close this. Thanks!
