### ISSUE TITLE
neutralButtonLabel not working

### ISSUE THREAD

**Issue by hufftheweevil** [react-native-community/datetimepicker#198]
# Bug report

## Summary

`neutralButtonLabel` does not display a button.

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
    Memory: 23.76 GB / 31.89 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
  npmPackages:
    react: ^16.12.0 => 16.12.0
    react-native: ^0.61.5 => 0.61.5
```

Library version: 2.4.2

## Steps to reproduce

Use DateTimePicker as such:
```
<DateTimePicker
  value={moment().toDate()}
  neutralButtonLabel='clear'
/>
```

Describe what you expected to happen:

1. A "CLEAR" button to appear on the picker in the bottom left.

Edit: Before anyone asks... yes I am aware this prop is only for Android, and I am using Android.

**Comment by luancurti** [comment]
@hufftheweevil you can provide more information about what version of Android you have tested and provide a reproducible demo (can be a repository here on github with the steps to reproduce)
