### ISSUE TITLE
DatePickere is not showing done and candle button in ios

### ISSUE THREAD

**Issue by kuldeepworkid** [react-native-community/datetimepicker#201]
# Question

**Comment by vonovak** [comment]
hello, sorry but I don't 100% understand what you're asking... If you need any "done" button, you'll have to create it yourself or use some other library that wraps around this one :) Hope this helps.

**Comment by Asinox** [comment]
But I can see at least on Android, Ok and Cancel buttons but without styles, white as the container component. How style those?!
