### ISSUE TITLE
How do I get the confirm / cancel button on IOS and customize the confirm / cancel button text?

### ISSUE THREAD

**Issue by zsy6504** [react-native-community/datetimepicker#214]
Hi guys, I noticed that on android there're default ok / cancel buttons on the pop-up. But on IOS I don't see any confirm / cancel buttons, there're no props for me to customize any, has anyone figured out how to do it on IOS?

**Comment by vonovak** [comment]
hello, thanks for asking! The ios date time picker does not have any confirm / cancel buttons, you have to create and style those by yourself.

Thank you!
