### ISSUE TITLE
[Question] Show date and time pickers at the same time?

### ISSUE THREAD

**Issue by Legym** [react-native-community/datetimepicker#215]
Hi there!

I'm really enjoying this plugin. Thank you for all the work! I have 4 inputs that ask the user to enter the starting day, ending day, starting time, and ending time. 

Is it possible to show the time and date picker at the same time? 

![Image from iOS (3)](https://user-images.githubusercontent.com/4462368/86981921-e9603a00-c155-11ea-9510-2134b8edfb50.png)

**Comment by rectified95** [comment]
@Legym It all comes down to whether the native platforms provide that functionality. Taking a quick glance at what Windows provides - https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/date-and-time - it's not currently possible, I don't know about the other platforms.  Android seems to have that separated, as well. 

You can try suggesting a feature extension to the native platforms, and if there are enough people reporting a similar need, it might get implemented. 
You can create an issue for the WinUI here: https://github.com/microsoft/microsoft-ui-xaml/issues

**Comment by Legym** [comment]
Thanks for your response @rectified95! Just wanted to make sure I didn't miss anything.
