### ISSUE TITLE
is24Hour not working on iOS 13

### ISSUE THREAD

**Issue by rynvva** [react-native-community/datetimepicker#220]
# Bug report

## Summary

I set the is24Hour to true, but it still give me 12 hours picker

## Environment info

`react-native info` output:

System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 435.51 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_241 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 2.6.0

## Steps to reproduce

try this code

```
<DateTimePicker
      testID = "dateTimePicker"
      value = {new Date()}
      mode = 'datetime'
      is24Hour = {true}
 />
```

on my machine still showing 12 hours option of picker and am/pm options

<img width="482" alt="Screen Shot 2020-07-13 at 16 04 55" src="https://user-images.githubusercontent.com/39117076/87286100-9a821e00-c522-11ea-94ce-2af21a2a48d4.png">

1. Install properly the library
2. try the code

Describe what you expected to happen:

1. when using is24Hour props to true, the picker should showing 24 hours options of picker

## Reproducible sample code

```
<DateTimePicker
      testID = "dateTimePicker"
      value = {new Date()}
      mode = 'datetime'
      is24Hour = {true}
 />
```

**Comment by rynvva** [comment]
it's also not working on ```mode = 'time'``` too

**Comment by rynvva** [comment]
oh my bad didn't read it before

<img width="443" alt="Screen Shot 2020-07-13 at 16 19 30" src="https://user-images.githubusercontent.com/39117076/87287739-ab339380-c524-11ea-8bef-73b22d512568.png">

**Comment by inimist** [comment]
> it's also not working on `mode = 'time'` too
> 
> <img alt="Screen Shot 2020-07-13 at 16 12 59" width="482" src="https://user-images.githubusercontent.com/39117076/87286966-ba661180-c523-11ea-87b3-004465afefe1.png">

I am not sure how did you produced this. I want to show time in 12 hours format but it wont show. It only shows in 24 hours format and the link you posted with your next comment "oh my bad didn't read it before" seems to mean that it is not possible to show time in 12 hour format in iOS. I am confused!?

**Comment by nald-dev** [comment]
@inimist at that time I want display it as 24 hour mode, but at that time 24 hour mode only support on Windows and Android, yeah I have no choose, so I display it as 12 hour mode

**Comment by kashif111777** [comment]
Yup Locale="en-UK" also works for me.
