### ISSUE TITLE
[iOS] Library not found RNDateTimePicker

### ISSUE THREAD

**Issue by R4DIC4L** [react-native-community/datetimepicker#224]
# Question

When trying to test this library on iOS, I am receiving the following error:
```
ld: warning: directory not found for option '-L-L/Users/netrom/Library/Developer/Xcode/DerivedData/MaradApp-buzxzgrwmouhlwfvewzrsctyzzdu/Build/Products/Debug-iphonesimulator/RNDateTimePicker'
ld: library not found for -lRNDateTimePicker
```

Has anyone else experienced this?

**Comment by mwahlig** [comment]
Did you run `npx pod-install` after installing the npm/yarn package? If not, you need to do so in order to install the associated `RNDateTimePicker` pod.

https://github.com/react-native-community/datetimepicker#getting-started

**Comment by R4DIC4L** [comment]
@mwahlig Thank you for your reply! I've run pod install command on the ios folder after installation. I think that's the same with the npx one.

**Comment by R4DIC4L** [comment]
Also tried manual linking of the package, but I have RN 0.60, so it shouldn't be needed. I still get the error.

**Comment by R4DIC4L** [comment]
I figured it out. Seems the library was missing from the **Header Search Paths** and **Library Search Paths**. Below is what I had to add, if anyone runs into this problem.

**Header Search Paths**
`"${PODS_ROOT}/Headers/Public/RNDateTimePicker"`

**Library Search Paths**
`"${PODS_CONFIGURATION_BUILD_DIR}/RNDateTimePicker"`
