### ISSUE TITLE
Datepicker text on physical iPhone is White

### ISSUE THREAD

**Issue by dmantelli** [react-native-community/datetimepicker#228]
When I show the Datepicker on iOS emulator, the text of the selectors (days, months and years) works correctly. But when I run on a physical iPhone, the text of that selectors appears in white color.

Screenshot on physical device:

![IMG_1DD61234FFDC-1](https://user-images.githubusercontent.com/23085950/88207357-07ce3700-cc26-11ea-9aca-e587168d633c.jpeg)

The code is this:

<img width="228" alt="Captura de Pantalla 2020-07-22 a la(s) 14 17 35" src="https://user-images.githubusercontent.com/23085950/88207444-2f250400-cc26-11ea-9b33-801d6e424c07.png">

Anyone has this issue too ?
Thanks

**Comment by vonovak** [comment]
hello @dmantelli does this help? https://github.com/react-native-community/datetimepicker/pull/204/files

**Comment by dmantelli** [comment]
> hello @dmantelli does this help? https://github.com/react-native-community/datetimepicker/pull/204/files

Yes, it does.
The solution was using the "textColor" property.
Just set it to "textColor='#000000'" and now it works perfect !

Thanks!
