### ISSUE TITLE
How to reopen date picker modal on Android device?

### ISSUE THREAD

**Issue by hakkikonu** [react-native-community/datetimepicker#231]
On ios it is embedded component but on android i see modal. When user selects a date, modal closes. How can I open date modal again?

My current component like this;

```
<RNDateTimePicker
              style={{flex: 1}}
              value={this.state.birthDate}
              minimumDate={new Date(1920, 0, 1)}
              maximumDate={new Date(this.getCurrentYear() - 10, 0, 1)}
              display="spinner"
              textColor="#fff"
              mode="date"
              onChange={(event, date) => this.handleBirthDate(event, date)}
            />
```

**Comment by karanmartian** [comment]
@hakkikonu You need to do it using state. Something like

this.state.open && <RNDateTimePicker

Set the state of your open variable accordingly as either true or false to display the modal again.

Also, one important question, I see that you are using spinner display here. Is it working for you in standalone app?

**Comment by hakkikonu** [comment]
@karanmartian thanks your comment. 

Yes spinner features working for me. There is no problem about it.

**Comment by luancurti** [comment]
You can follow the [basic usage](https://github.com/react-native-community/datetimepicker#basic-usage-with-state) the setShow state control if the picker is hide or not
