### ISSUE TITLE
minuteInterval is not working in 'time' mode

### ISSUE THREAD

**Issue by ShayGit** [react-native-community/datetimepicker#238]
Hello, I am using the time picker but the minuteInterval is not working for me both on default and spinner displays.
```
  const [isTimePickerVisible, setIsTimePickerVisible] = useState(false);
  const [minuteInterval, setMinuteInterval] = useState(5);

 {isTimePickerVisible && (
              <DateTimePicker
                mode="time"
                value={new Date()}
                is24Hour={true}
                minuteInterval={minuteInterval}
                display='default'
                onChange={(event, date) => {
                  setIsTimePickerVisible(false);
                  if (date != undefined) {
                    let hours = date.getHours();
                    let minutes = date.getMinutes();
                    //const seconds = time.getSeconds();
                    if(hours<7 || hours > 16 || (hours === 16 && minutes !== 0))
                    {
                      wrongWorkingHoursAlert();
                    }
                      else{
                    if (hours.toString().length !== 2) hours = "0" + hours;
                    if (minutes.toString().length !== 2)
                      minutes = "0" + minutes;
                    setTimeString(hours + ":" + minutes);
                      }
                  }
                }}
              />
            )}
```

![image](https://user-images.githubusercontent.com/26070570/89187647-3c3adf00-d5a6-11ea-88a9-38256f77d2b7.png)

Would like to know if I am doing somthing wrong since I do not see any report about this issue.
Thanks.

Using Expo
RN Version: 0.62.2
OS: Android emulator and phone ( not checked on ios yet )
Library version: 2.6.1

**Comment by rectified95** [comment]
@ShayGit Can you test this on **2.6.0** and tell us you the issue there, as well? It'd be greatly appreciated!

**Comment by ShayGit** [comment]
> @ShayGit Can you test this on **2.6.0** and tell us you the issue there, as well? It'd be greatly appreciated!

Still not working on 2.6.0, maybe it is related to expo compatibility? 
I am getting this warning: 
```
Some of your project's dependencies are not compatible with currently installed expo package version:
 - @react-native-community/datetimepicker - expected version range: 2.4.0 - actual version installed: ^2.6.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
```

**Comment by luancurti** [comment]
The latest version in the expo is `2.4.3` according this [PR](https://github.com/expo/expo/pull/9543) and the implementation of the feature is in the `2.5.0` according the [CHANGELOG](https://github.com/react-native-community/datetimepicker/blob/master/CHANGELOG.md#250) need to update in the expo the `datetimepicker` version

**Comment by spyshower** [comment]
@vonovak Still not working in 3.0.1 (not using Expo)

**Comment by vonovak** [comment]
@spyshower yes, your edit is correct. We cannot control values that can be selected, so we correct the value after selection.

if this does not work for someone, please open a new issue according to the template, thanks
