### ISSUE TITLE
What the differences between @react-native-community/datetimepicker to react-native-modal-datetime-picker

### ISSUE THREAD

**Issue by idanlevi1** [react-native-community/datetimepicker#240]
# Question

Maybe it's a fool question but i have those two packages in my project and i 
wondering what the differences between `@react-native-community/datetimepicker` to `react-native-modal-datetime-picker`  ?

**Comment by vonovak** [comment]
hello, thanks for asking. `react-native-modal-datetime-picker` is a wrapper over `@react-native-community/datetimepicker`.

Since I'm not familiar with that library, this is the best answer I can give. Thanks!
