### ISSUE TITLE
Yarn install error

### ISSUE THREAD

**Issue by HDDRT** [react-native-community/datetimepicker#243]
Hi!

I have a problem. When I try to install datetimepicker I received an error like this:
 
`error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-community%2fdatetimepicker: Not found".
`

**Comment by merouan95** [comment]
same

**Comment by khryshyn** [comment]
Just stopped work

**Comment by Gogoro** [comment]
Same here

**Comment by Gogoro** [comment]
Looks like npm might have some issues right now 😢  [https://status.npmjs.org/](https://status.npmjs.org/)

**Comment by luancurti** [comment]
Now it is ok?

**Comment by Gogoro** [comment]
Works again now 👍
