### ISSUE TITLE
Exception thrown on iOS 14 beta if textColor is set

### ISSUE THREAD

**Issue by jan-happy** [react-native-community/datetimepicker#247]
# Bug report
## Summary

If you set the textColor property on the latest iOS 14 beta (18A5342e) the following exception is thrown:

`Exception thrown while executing UI block: -[_UIDatePickerIOSCompactView setHighlightsToday:]: unrecognized selector sent to instance 0x7f7fc7e0ddc0

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1112
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.461
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0
`

## Environment info

`react-native info` output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.15.5
      Memory: 909.69 MB / 32.00 GB
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 16, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
```

Library version: 2.6.1

## Reproducible sample code

```bash
<DateTimePicker
   value={new Date()}
   mode={'time'}
   textColor="#000000"  
   display="default"
   onChange={(event, date) => {
     console.log(date);
 }}
/>
```

**Comment by nimabrownlee** [comment]
@vonovak This is unfortunately not fixed in 3.0.8.

**Comment by acrdlph** [comment]
@nimabrownlee works for me, when setting `display="spinner"` (which is a pre-requisite for the textColor to have any effect according to documentation)

**Comment by nimabrownlee** [comment]
@acrdlph Sorry but still isn't working. Tried to remove node_modules and re-install everything but it doesn't fix it.

**Comment by ivanjzr** [comment]
Same problem here, removed modules and nothing, this error came out of nothing

**Comment by ivanjzr** [comment]
In Expo I did "expo r -c" and did not work either.

**Comment by ivanjzr** [comment]
You need to open this issue again as I did what @vonovak said, I updated from version 2.4 to "@react-native-community/datetimepicker": "3.0.1" and did not work either

**Comment by stefan-girlich** [comment]
The issue still exists for me using the following setup:
- `@react-native-community/datetimepicker` 3.0.9
- iPhone X
- iOS 14.2

**Comment by MarcHbb** [comment]
Please any suggestion to fix this ?

**Comment by auliakbarh** [comment]
<img width="332" alt="Screen Shot 2021-01-22 at 23 47 17" src="https://user-images.githubusercontent.com/5032631/105519575-29f75d80-5d0c-11eb-9854-7db8da4d8d6c.png">


is this the same issue?

**Comment by stefan-girlich** [comment]
@auliakbarh This is the same error according to the matching error messages. Feel free to remove your message and screenshot.
@vonovak Would you be able to provide a brief update on the progress on this issue? I'm also happy to support wherever I can; just let me now.

**Comment by vonovak** [comment]
hello, the issues described are the same as in #308 so I will lock this issue so that we don't have 2 places talking the same thing; discussion can continue there.

The fix I'd like to see is outlined in this comment https://github.com/react-native-datetimepicker/datetimepicker/issues/308#issuecomment-739564472. @stefan-girlich if you want to take a look at it, you're very welcome to do so :). Otherwise I will circle back to this at some point when we have more "money in the bank" (we currently have $4.30) from our sponsors (as discussed in #313).
