### ISSUE TITLE
is24Hour is being overwritten by device default settings

### ISSUE THREAD

**Issue by TylerKnvpp** [react-native-community/datetimepicker#248]
# Bug report

## Summary

**Platform**: iOS

**Issue:** 

is24Hour is being overwritten by the device's default settings. For a code sample, you can replicate by copying and pasting the "Basic Usage" example.

**Comment by vonovak** [comment]
hello and thanks for reporting;

the prop is only supported on android and windows, as documented: https://github.com/react-native-community/datetimepicker#is24hour-optional-windows-and-android-only
