### ISSUE TITLE
Change the background color of the picker

### ISSUE THREAD

**Issue by Softkeydel** [react-native-community/datetimepicker#254]
# Question

How to change the background color of the picker??
Please help asap

**Comment by ishaqashraf** [comment]
+1

**Comment by vonovak** [comment]
hello, on iOS, just pass the `style` prop; on Android, I this is currently not exposed, although you may be able to influence the styling via some xml styles: https://github.com/react-native-community/datetimepicker/issues/20#issuecomment-545527682

hope this helps!

**Comment by Softkeydel** [comment]
@vonovak 
Thanks
