### ISSUE TITLE
after pod installation for react native date time picker build getting failed 

### ISSUE THREAD

**Issue by arun1705** [react-native-community/datetimepicker#255]
# Bug report

## Summary
after doing pod installation react native app build getting failed

## Environment info

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 38.29 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/hemanthosamani/.rvm/rubies/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:  *react-native*: Not Found

Library version: v3.0.0

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

## Reproducible sample code

<img width="1440" alt="Screenshot 2020-08-16 at 12 38 38 PM" src="https://user-images.githubusercontent.com/41661371/90328851-70a69600-dfbd-11ea-926d-ecf918fe4618.png">

**Comment by vonovak** [comment]
hello, sorry, we didn't make it clear, but we tested this with latest xcode 11, that is 11.6

please upgrade to latest xcode 11, thank you!
