### ISSUE TITLE
RNDatePicker Not found in UIManager

### ISSUE THREAD

**Issue by Gabogg07** [react-native-community/datetimepicker#256]
# Bug report

## Summary

After following the installation steps (npm install and then npx pod-install) my app either fails at build with RNDatPicker Not found in UIManager, or build and shows the error when trying to use the component

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    Memory: 57.10 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.0

## Steps to reproduce

Explained in Summary

Describe what you expected to happen:

1. I can use the DatePicker component
2. …

## Reproducible sample code

![image](https://user-images.githubusercontent.com/22857185/90539948-5a234a80-e135-11ea-9484-493e981a6814.png)

**Comment by vonovak** [comment]
hello, sorry, we didn't make it clear, but we tested this with latest xcode 11, that is 11.6

please upgrade to latest xcode 11, thank you!

**Comment by ZainaliSyed** [comment]
> hello, sorry, we didn't make it clear, but we tested this with latest xcode 11, that is 11.6

@vonovak  is there any other solution available rather than **updating XCODE**  

XCODE VERISON : 11.3.1

**Comment by Gabogg07** [comment]
@ZainaliSyed I used the latest 2.x version of the library because I needed to go forward with the project. The fixes for V. 3.X were not limiting for my needs, maybe it works for you too
