### ISSUE TITLE
IOS Build Error with 3.0.1

### ISSUE THREAD

**Issue by SunSet1219** [react-native-community/datetimepicker#261]
npm i react-native-modal-datetime-picker @react-native-community/datetimepicker
npx pod-install
RN version: 0.63.2

![image](https://user-images.githubusercontent.com/26632694/91205537-6481ad80-e70e-11ea-8fe7-28fafa676a1c.png)

**Comment by brunocolm** [comment]
I have the same problem

**Comment by vonovak** [comment]
hello, please use latest stable XCode (11.6), thank you!
