### ISSUE TITLE
Can't select year in "datetime" mode in IOS

### ISSUE THREAD

**Issue by huzaima** [react-native-community/datetimepicker#262]
In "datetime" mode, there is no option to select year. Can someone please help in how I can also show year in this picker? Screenshot attached for reference.

<img width="324" alt="Screenshot 2020-08-26 at 4 21 53 PM" src="https://user-images.githubusercontent.com/17503685/91297902-89325f80-e7b8-11ea-92c3-83199dec37ad.png">

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.04 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.21.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by vonovak** [comment]
hello, unfortunately, no such mode is provided by apple. see https://developer.apple.com/documentation/uikit/uidatepickermode?language=objc

you can use `UIDatePickerModeDate` (pass "date") but you'll not get time selection

thank you!
