### ISSUE TITLE
[Android]Can't display current date more than 31/12/2100

### ISSUE THREAD

**Issue by hondaholics** [react-native-community/datetimepicker#265]
# Bug report
I set value to 02/09/2563 but Date picker can't display  2563 year
<img width="184" alt="Screen Shot 2563-09-02 at 17 09 41" src="https://user-images.githubusercontent.com/5014284/91968634-1c324300-ed3f-11ea-983f-54a29263b367.png">

**Comment by cornelRaiu** [comment]
[Here is the reason why](https://stackoverflow.com/questions/5879173/why-do-timestamps-have-a-limit-to-2038) you can not select any date after 2038

**Comment by vonovak** [comment]
hello, closing as answered. ^ 
Thanks!
