### ISSUE TITLE
IOS build error on react-native 0.63.2 

### ISSUE THREAD

**Issue by MrtYlnzz** [react-native-community/datetimepicker#266]
I can't build my application anymore after adding the package and pod installing. Anything I am doing wrong? 

![Screen Shot 2020-09-02 at 19 34 24](https://user-images.githubusercontent.com/6218537/92011298-8bb22d80-ed53-11ea-8071-030272fc3043.png)

**Comment by vonovak** [comment]
hello, this is likely the same as https://github.com/react-native-community/datetimepicker/issues/261

thanks!
