### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by iqorlobanov** [react-native-community/datetimepicker#273]
Hi everyone. 
I can't run my project after installing datepicker
React Native version 0.63.2

<img width="1033" alt="Screen Shot 2020-09-10 at 15 01 52" src="https://user-images.githubusercontent.com/3371179/92721811-b6b20800-f377-11ea-839e-8e7f26473d91.png">

**Comment by gazedash** [comment]
Duplicates #270 #189
@iqorlobanov what Xcode version are you on?

For me it works on 11.7 and 12 beta, I had this problem on CI, we updated Xcode to 11.6 and the problem was resolved

**Comment by iqorlobanov** [comment]
> Duplicates #270 #189
> @iqorlobanov what Xcode version are you on?
> 
> For me it works on 11.7 and 12 beta, I had this problem on CI, we updated Xcode to 11.6 and the problem was resolved

I'll try to update my Xcode to 11.7
Previous version was 11.3

**Comment by iqorlobanov** [comment]
Its working on Xcode 11.7, thanks @gazedash
