### ISSUE TITLE
value for value cannot be cast from string to double

### ISSUE THREAD

**Issue by rananajam1** [react-native-community/datetimepicker#277]
# Bug report

## Summary

value for value cannot be cast from string to double

## Environment info

`react-native info` output:

```bash
# System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 4.51 GB / 15.88 GB
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_211
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.2

## Steps to reproduce

Error on component launch

1. Pass date "new Date()" via state in class component gives error "value for value cannot be cast from string to double"
2. Providing "new Date()" to the "value" prop directly works fine

## Reproducible sample code

          <DateTimePicker
            mode="date" 
            value={this.state.chosenDate}  //initialize state as "new Date()" in the constructor
            onChange={this.handlePicker}
            display="default"
          />

**Comment by luancurti** [comment]
@rananajam1 can you provide the full source code from this component?

**Comment by lumberman** [comment]
Having the same problem with Android only. Works well con iOS.

**Comment by lumberman** [comment]
![Screen Shot 2020-11-09 at 10 42 20 AM](https://user-images.githubusercontent.com/1384471/98555388-40972800-2278-11eb-8157-bc6b305bbf95.png)

**Comment by pendihu** [comment]
I had the same issue. Solved it using Date.parse() and moment like this:

```
setMyDate(new Date(
  Date.parse(
    moment(props.myDate, 'YYYY-MM-DD').format(
      'ddd MMM DD YYYY'
    )
  )
));
```

Found the solution from here: 
https://stackoverflow.com/questions/53711487/react-native-error-value-for-date-cannot-be-cast-from-string-to-double

**Comment by WarrenBuffering** [comment]
Can confirm. I believe this is because you're trying to pass a String via `value` when it's expecting a timestamp. Though if I recall correctly, you're unable to pass a timestamp to the iOS version. It would feel more appropriate to have this shared DatePicker component handle the parsing per native OS, and the component itself should just expect a Date object.
