### ISSUE TITLE
Why on iOS 14 display='default' doesn't work? I had to use display='spinner'

### ISSUE THREAD

**Issue by victor871129** [react-native-community/datetimepicker#280]
The code for calculate the height has getDefaultDisplayValue that returns null. 
That is for mode different than countdown.
![20200917 140507 PC-01](https://user-images.githubusercontent.com/284717/93516839-339d2e80-f8f0-11ea-95a2-84acee17d737.png)

**Comment by vonovak** [comment]
hello and thanks for reporting,
I'm sorry, but I don't understand what this issue is about.

Please open a new issue and follow the issue template, thanks!
