### ISSUE TITLE
Input parameter second on Time Picker

### ISSUE THREAD

**Issue by never00miss** [react-native-community/datetimepicker#59]
# Feature Request
Hello, is there any timepicker that can pick a second on timepicker?
i confuse that there is no props second on this timepicker that can enable second picker.
 
<img width="284" alt="Screen Shot 2019-11-28 at 16 33 10" src="https://user-images.githubusercontent.com/10415043/69794437-d4551d00-11fc-11ea-9294-0dec341fabab.png">

this is simple request, but necessary on my feature that, sales can be pick a second

**Comment by vonovak** [comment]
hello, the native picker dialog does not support this, so I'm closing this as wontfix, as per [this note](https://github.com/react-native-community/datetimepicker#props). Thank you.
