### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager

### ISSUE THREAD

**Issue by hengvenchang** [react-native-community/datetimepicker#70]
When i run "react-native run-ios"! the component seems to work just fine!
But when i run "detox test", i got this error:

Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager

Is this plugin not usable with detox?

**Comment by joecervino** [comment]
+1

**Comment by LukeXF** [comment]
+1

**Comment by rafaelcavalcante** [comment]
Duplicated from #12

**Comment by vonovak** [comment]
hello, this is most likely problem with linking the module. I'm closing this because there is no runnable reproduction. 

please create a new issue with repro and we'll be happy to review it!
