### ISSUE TITLE
Include the day of the week in "date" mode

### ISSUE THREAD

**Issue by YPCrumble** [react-native-community/datetimepicker#75]
Thanks for maintaining this repo!

What I'd like is to include the day of the week (e.g., Mon/, Tues.) in "date" mode for iOS. I understand that for iOS it's possible to get the day of the week in "datetime" mode - what I'm looking for is just the day of the week and the date. Android doesn't have the same issue because it shows the entire calendar with day of the week abbreviations at the top.

For example, it would make it easier for the user to understand the date they're choosing based on whether it's a weekday or weekend day.

I searched for and couldn't find a way to override the labels. If helpful I'd be happy to contribute a PR if maintainers have a good idea on the best implementation. 

Thanks again!

**Comment by sddddgjd** [comment]
I've also run into this issue and would love if you guys could add such functionality!

**Comment by vonovak** [comment]
hello, based on https://developer.apple.com/documentation/uikit/uidatepicker/mode, I do not believe this is possible via the `mode` prop. You'll probably have to create your own picker for this. 

Alternatively, what might help is this: https://developer.apple.com/documentation/uikit/uidatepickerstyle which will be implemented in #211

**Comment by sddddgjd** [comment]
Awesome! I didn't nec want it through the mode prop but I am glad there's something in the works!
